---
abstract: 'Higher-level UA features for HTTP::Tiny'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0'
  IO::Dir: '0'
  IO::File: '0'
  IO::Socket::INET: '0'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny-UA
no_index:
  directory:
    - corpus
    - examples
    - t
    - xt
  package:
    - DB
provides:
  HTTP::Tiny::UA:
    file: lib/HTTP/Tiny/UA.pm
    version: '0.006'
  HTTP::Tiny::UA::Response:
    file: lib/HTTP/Tiny/UA/Response.pm
    version: '0.006'
requires:
  Class::Tiny: '1.000'
  HTTP::Tiny: '0.036'
  perl: '5.006'
  strict: '0'
  subs: '0'
  superclass: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/HTTP-Tiny-UA/issues
  homepage: https://github.com/dagolden/HTTP-Tiny-UA
  repository: https://github.com/dagolden/HTTP-Tiny-UA.git
version: '0.006'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Felipe Gasper <felipe@felipegasper.com>'
  - 'Graham Ollis <perl@wdlabs.com>'
  - 'Michael G. Schwern <schwern@pobox.com>'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.70'
