Vítejte v TeX Live
 	
	   Softwarová distribuce TeX Live nabízí kompletní TeXový systém
	   pro řadu platforem - GNU a UNIX, Macintosh, Windows a další.
	   Zahrnuje programy pro editování, sazbu, zobrazení a tisk
	   TeXových dokumentů v mnoha různých jazycích a rozsáhlou
	   kolekci TeXových maker a fontů.
 	
	   Distribuce zahrnuje obsáhlou dokumentaci o TeXu obecně,
	   stejně jako dokumentaci k zahrnutým softwarovým balíkům.
 	
	   Informaci o licencích najdete v kořenovém adresáři v
	   textových souborech [1]LICENSE.TL a [2]LICENSE.CTAN.
 	  
	Kde začít
 	
	   Důrazně doporučujeme, abyste si ještě před instalací přečetli
	   průvodce TeX Live. Průvodce obsahuje instrukce "krok za
	   krokem", popis hlavních adresářů a další informace.
 	
	   Pokud instalujete z DVD, anglické i další jazykové verze
	   instalačních průvodců jsou umístěny v podadresáři
	   [3]texlive-doc.
 	 
	   Po instalaci, anglické verze Průvodce instalací najdete v
	   adresářové struktuře [4]texmf-dist/doc/texlive ve formátech
	   [5]html i [6]pdf.  Překlady do dalších jazyků jsou také
	   dostupné v podstromu [7]texmf-dist/doc/texlive.
 	
	   Nabízíme také [8]seznam odkazů na dostupnou dokumentaci k
	   zahrnutým balíkům a programům, opět ve formátech HTML a PDF.
 	
	   Pokud instalujete z internetu, výše zmíněné odkazy vám
	   nebudou fungovat.  V tom případě si ale můžete [9]dokumentaci
	   TeX Live prohlížet na internetu.
 	
	   Seznam nejdůležitějších změn v letošním vydání najdete v
	   oddílu Historie verzí na konci dokumentace.
 	
	Instalace
 	
	   Instalační program (skript) se nazývá install-tl a je na nejvyšší
	   úrovni stromu adresářů.

	   Můžete to vyvolat pomocí perlinstall-tl. V systému Windows můžete
	   spustit připojený dávkový soubor (install-tl-windows.bat. V
	   počítačích Mac je pravděpodobně nejlepší jej nainstalovat pomocí
	   [10] MacTeX, který má svůj vlastní nativní instalační program (je
	   také na DVD, podél poslat text, že jste teď.)

   	   install-tl má dva režimy provozu:

	   -gui (předdefinováno v systémech Windows a Mac), které provádí
	   standardní snadnou instalaci pomocí grafického rozhraní, které však
	   v případě potřeby umožňuje mnoho pokročilých možností.

	   -no-gui (předdefinováno ve všech ostatních operačních systémech),
	   které poskytuje všechny dostupné možnosti pomocí zjednodušeného
	   grafického textového rozhraní.

	Poinstalační aktualizace balíčků jsou stejně jako jiné konfigurace
	prováděny pomocí programu (skript) tlmgr (TeX Live Package Manager),
	který funguje také v obou režimech: text a GUI.

	Na příkazovém řádku můžete spustit volbu --help pro: [11] install-tl a
	[12] tlmgr, která poskytuje podrobnější informace o těchto programech.
	Další informace naleznete v odkazech na dokumentaci výše.
	   
	 Nakonec několik webových stránek, pro informaci. Tyto stránky nejsou
	 součástí TeX Live:

Odkazy

          * [13] https://tug.org/begin.html - pokud jste začátečník TeX
            a / nebo chcete úvodní materiál.
          * [14] https://tug.org/interest.html - obecný seznam na webu
            Prostředky TeX, včetně dokumentace, systémů,
            balíčky, písma a další.
          * [15] https://tug.org/ctan.html - vstupní bod v
            Komplexní síť TeX Archive Network (CTAN), což je a
            úložiště všech věcí souvisejících s TeXem.
          * [16] https://tug.org/usergroups.html - seznam skupin
            Uživatelé TeXu z celého světa, s informacemi od
            kontakt. Důrazně žádáme, abyste se připojili
            uživatelská skupina podle vašeho výběru, za účelem podpory TeX Live
            a další aktivity TeXu.
	  * [17]https://www.cstug.cz. Podpoříte tím TeX Live a další TeXové aktivity.

Příjemné TeXování!

            ___________________________________________________________

          [18] TeX Live stránka na webu.

Reference
	   
	   1. file:../LICENSE.TL
 	   2. file:../LICENSE.CTAN
 	   3. file:../texlive-doc
 	   4. file:../texmf-dist/doc/texlive/texlive-en
 	   5. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.html
 	   6. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.pdf
 	   7. file:../texmf-dist/doc/texlive/
 	   8. file:../doc.html
 	   9. https://tug.org/texlive/doc.html
	  10. https://tug.org/mactex/
 	  11. https://tug.org/texlive/doc/install-tl.html
 	  12. https://tug.org/texlive/tlmgr.html
 	  13. https://tug.org/begin.html
 	  14. https://tug.org/interest.html
 	  15. https://tug.org/ctan.html
 	  16. https://tug.org/usergroups.html
 	  17. https://www.cstug.cz
 	  18. https://tug.org/texlive/ 
	   
