---
abstract: "Interface to the Let's Encrypt ACME API"
author:
  - 'Stephen Ludin <sludin@ludin.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Protocol-ACME
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::Format: '0.04'
  Crypt::OpenSSL::Bignum: '0.04'
  Crypt::OpenSSL::RSA: '0.28'
  Crypt::RSA::Parse: '0.02'
  Digest::SHA: '5.88'
  HTTP::Tiny: '0.050'
  JSON: '2.61'
  Log::Any: '0.15'
  Log::Any::Adapter: '0.11'
  Test::Exception: '0.35'
  perl: '5.007003'
resources:
  repository: https://github.com/sludin/Protocol-ACME.git
version: '0.12'
