---
abstract: 'Conversion utilities for encryption applications'
author:
  - 'Felipe Gasper (FELIPE)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0.4'
  Test::More: '1'
  Test::Simple: '0.44'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Format
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: '0.01'
resources:
  repository: https://github.com/FGasper/p5-Crypt-Format.git
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
