---
abstract: 'A class for creating Pod to Wiki filters.'
author:
  - 'John McNamara (jmcnamara@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Simple-Wiki
no_index:
  directory:
    - t
    - inc
requires:
  Pod::Simple: '0'
resources:
  bugtracker: http://github.com/jmcnamara/pod-simple-wiki/issues
  homepage: http://jmcnamara.github.com/pod-simple-wiki/
  repository: http://github.com/jmcnamara/pod-simple-wiki
version: '0.20'
