# $Id: Makefile 890 2023-01-21 02:05:59Z karl $
# Public domain.
# Test shipout keyword on \special and \pdfliteral.

include ../Common.mak

test-shipout:
	$(prog) -etex ./test-shipout.tex

clean:
	$(clean)

