---
abstract: 'Manipulate and anaylze tree structured data.'
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Tree
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08100
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://git.shadowcat.co.uk/gitweb/gitweb.cgi?p=dbsrgits/DBIx-Class-Tree.git
version: 0.03003
