---
abstract: 'Adds automatically an ETag header.'
author:
  - 'Franck Cuny <franckcuny@gmail.com>'
build_requires:
  HTTP::Request::Common: '0'
  Plack::Builder: '0'
  Plack::Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-ETag
requires:
  Digest::SHA: '0'
  Plack::Middleware: '0'
  Plack::Util: '0'
  Plack::Util::Accessor: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/franckcuny/plack-middleware-etag/issues
  homepage: http://search.cpan.org/perldoc?Plack::Middleware::ETag
  repository: https://github.com/franckcuny/plack-middleware-etag
version: '0.05'
x_Dist_Zilla:
  perl:
    version: '5.020002'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@Filter/GatherDir'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Filter/MakeMaker'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: Test::NoTabs
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
          trailing_whitespace: '1'
      name: Test::EOL
      version: '0.18'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.012'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.012'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.012'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.012'
      name: PodWeaver
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.037'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.037'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.037'
